#!/usr/bin/env julia
#
# Re-record the recorded server responses in test/fixtures.
#
#     julia --project=. test/record_fixtures.jl
#
# Fixtures are stored as raw server bytes, because the quirks they exist to pin (TAXSIM 32's
# trailing comma on full-detail rows, TAXSIM 35's space-padded header names, the HTTP endpoint's
# leading blank line) are invisible once parsed. Each one gets a sidecar .toml recording what
# was submitted and which server build answered, so staleness is visible without guessing.
#
# Run this when a live canary test fails. A diff in the recorded bytes is a real change on
# NBER's side, not a test to relax.

using Taxsim, DataFrames, Dates
const T = Taxsim
const FIX = joinpath(@__DIR__, "fixtures")

const SPECS = (
    (name = "v32_default_nostate", version = 32, full = false,
     df = DataFrame(year = 1980, mstat = 2, ltcg = 100_000)),
    (name = "v32_full_nostate", version = 32, full = true,
     df = DataFrame(year = 1980, mstat = 2, ltcg = 100_000)),
    (name = "v32_full_state", version = 32, full = true,
     df = DataFrame(year = 1980, mstat = 2, pwages = 0, ltcg = 100_000, state = 1)),
    (name = "v32_full_2rows", version = 32, full = true,
     df = DataFrame(year = [1980, 1981], mstat = [2, 1], pwages = [0, 100_000],
                    ltcg = [100_000, 0], state = [1, 5])),
    (name = "v32_error_badyear", version = 32, full = false,
     df = DataFrame(year = 2025, mstat = 2, pwages = 100_000)),
    (name = "v35_default_nostate", version = 35, full = false,
     df = DataFrame(year = 1980, mstat = 2, ltcg = 100_000)),
    (name = "v35_full_nostate", version = 35, full = true,
     df = DataFrame(year = 1980, mstat = 2, ltcg = 100_000)),
    (name = "v35_full_state", version = 35, full = true,
     df = DataFrame(year = 1980, mstat = 2, pwages = 0, ltcg = 100_000, state = 1)),
    # The pair below pins the finding that 32 and 35 are different frozen builds: they agree on
    # 2022 federal tax and disagree on California state tax.
    (name = "v32_2022_ca", version = 32, full = false,
     df = DataFrame(year = 2022, mstat = 2, state = 5, pwages = 200_000)),
    (name = "v35_2022_ca", version = 35, full = false,
     df = DataFrame(year = 2022, mstat = 2, state = 5, pwages = 200_000)),
)

version_of(n) = n == 32 ? T.TAXSIM32 : T.TAXSIM35

banners = Dict(v => T.taxsim_server_version(v) for v in (32, 35))
for (v, b) in banners
    println("TAXSIM $v server: $b")
end

mkpath(FIX)
for spec in SPECS
    v = version_of(spec.version)
    table = T._table(spec.df, v, spec.full, T.DEFAULT_MTR)
    raw = T._submit(v, table; connection = :ssh_only)

    write(joinpath(FIX, spec.name * ".csv"), raw)

    lines = [l for l in split(replace(raw, "\r\n" => "\n"), '\n') if !isempty(strip(l))]
    header_fields = isempty(lines) ? 0 : count(==(','), lines[1]) + 1
    row_fields = length(lines) < 2 ? 0 : count(==(','), lines[2]) + 1

    open(joinpath(FIX, spec.name * ".toml"), "w") do io
        println(io, "# Generated by test/record_fixtures.jl - do not edit by hand.")
        println(io, "name           = ", repr(spec.name))
        println(io, "taxsim_version = ", spec.version)
        println(io, "server_banner  = ", repr(banners[spec.version]))
        println(io, "recorded_at    = ", repr(string(now())))
        println(io, "idtl           = ", table.idtl[end])
        println(io, "mtr            = ", repr(string(T.DEFAULT_MTR)))
        println(io, "rows_sent      = ", length(table.idtl))
        println(io, "header_fields  = ", header_fields)
        println(io, "row_fields     = ", row_fields)
        println(io, "submission     = ", repr(T._payload_string(table)))
    end
    println("  $(spec.name): $(length(raw)) bytes, header $header_fields / row $row_fields")
end
println("\nDone. Review `git diff test/fixtures` - any change is a change on NBER's side.")
